trigger:
- main

pool: Default

variables:
- group: GitHubSecrets       # secret variable group
- name: imageName
  value: 'omardiablo/auredevops'
- name: tag
  value: '$(Build.BuildId)'
- name: BuildSourcesDirectory
  value: '$(Build.SourcesDirectory)'

steps:
- checkout: self
  fetchDepth: 0   # fetch full repo history

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      latest

- task: SSH@0
  inputs:
    sshEndpoint: 'my-vm-ssh-connection'  
    runOptions: 'commands'
    commands: |
      echo "Hello from Azure DevOps"
      docker ps

- script: |
    git checkout main
    git config user.name "Omaur"
    git config user.email "omaraldeeb7@gmail.com"
    git add .
    git commit -m "Auto-commit from Azure DevOps" || echo "No changes to commit"
    git push https://$(GITHUB-TOKEN)@github.com/Omaur/Dockerfile.git main
  displayName: "Push changes to GitHub"
