trigger:
- main

pool: Default

variables:
- group: GitHubSecrets       # secret variable group
- name: imageName
  value: 'omardiablo/auredevops'
- name: tag
  value: '$(Build.BuildId)'
- name: BuildSourcesDirectory
  value: '$(Build.SourcesDirectory)'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'   # If Dockerfile is at repo root
    buildContext: '$(Build.SourcesDirectory)'            # Build context = repo root
    tags: |
      latest

- script: |
    git config user.name "Omaur"
    git config user.email "omaraldeeb7@gmail.com"
    git add .
    git commit -m "Auto-commit from Azure DevOps"
    git push https://$(GITHUB_PAT)@github.com/Omaur/Dockerfile.git HEAD:main
  displayName: "Push changes to GitHub"
