trigger:
- main

pool: Default

variables:
  imageName: 'Omaur/dockerhub'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Omaur/Dockerfile'   # correct Dockerfile path
    buildContext: 'Omaur'            # folder with app code
    tags: |
      latest
      $(tag)